export const SIGN_UP = 'SIGN_UP'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE'

export const SIGN_IN = 'SIGN_IN'
export const SIGN_CURRENT_USER = 'SIGN_CURRENT_USER'
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE'

export const GET_KITCHENS = 'GET_KITCHENS'
export const KITCHENS_RECEIVED = 'KITCHENS_RECEIVED'
export const KITCHENS_FAILURE = 'KITCHENS_FAILURE'

export const KITCHENS_DELETE = 'KITCHENS_DELETE'
export const DELETE_KITCHEN = 'DELETE_KITCHEN'
export const KITCHENS_DELETE_FAILURE = 'KITCHENS_DELETE_FAILURE'

export const KITCHENS_ADD = 'KITCHENS_ADD'
export const KITCHENS_ADDED = 'KITCHENS_ADDED'
export const KITCHENS_ADD_FAILURE = 'KITCHENS_ADD_FAILURE'

export const KITCHENS_EDIT = 'KITCHENS_EDIT'
export const EDITED_KITCHENS = 'EDITED_KITCHENS'
export const KITCHENS_EDITED_FAILURE = 'KITCHENS_EDITED_FAILURE'



