export const SIGN_UP = 'SIGN_UP'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE'

export const SIGN_IN = 'SIGN_IN'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE'

export const GET_KITCHENS = 'GET_KITCHENS'
export const KITCHENS_RECEIVED = 'KITCHENS_RECEIVED'
export const KITCHENS_FAILURE = 'KITCHENS_FAILURE'

export const DELETE_KITCHEN = 'DELETE_KITCHEN'
export const KITCHEN_DELETED = 'KITCHEN_DELETED'
export const KITCHEN_DELETE_FAILURE = 'KITCHEN_DELETE_FAILURE'

export const ADD_KITCHEN = 'ADD_KITCHEN'
export const KITCHEN_ADDED = 'KITCHEN_ADDED'
export const KITCHEN_ADDED_FAILURE = 'KITCHEN_ADDED_FAILURE'

export const EDIT_KITCHEN = 'EDIT_KITCHEN'
export const KITCHEN_EDITED = 'KITCHEN_EDITED'
export const KITCHEN_EDITED_FAILURE = 'KITCHEN_EDITED_FAILURE'

export const GET_RESTAURANTS = 'GET_RESTAURANTS'
export const RESTAURANTS_RECEIVED = 'RESTAURANTS_RECEIVED'
export const RESTAURANTS_FAILURE = 'RESTAURANTS_FAILURE'

export const ADD_RESTAURANT = 'ADD_RESTAURANT'
export const RESTAURANT_ADDED = 'RESTAURANT_ADDED'
export const RESTAURANT_ADD_FAILURE = 'RESTAURANT_ADD_FAILURE'

